version: '3.8'

services:
  # 1. The FastAPI Backend
  web:
    build: .
    container_name: weather_pro_api
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  # 2. The Streamlit Frontend
  frontend:
    build: ./frontend
    container_name: weather_pro_frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - web
    restart: unless-stopped

  # 3. The Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: weather_pro_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - frontend
    restart: unless-stopped